### PR TITLE
StackedInline Improvements

### PR DESCRIPTION
**Pull request by rafalp**
This is PR that intends to resolve issues with `StackedInline` handling reported in #389:

- Fields aren't full-width in StackedInline forms, instead they go for minimal possible size and require scrolling to read full contents for longer inputs.
- StackedInline forms themselves aren't visually obvious and thus induce certain eyestrain on administrators working with admin forms containing numerous StackedInline items.

**Todo**

* [x] Add visually distinctive border around StackedInline items
* [x] Add visually distinctive headings for StackedInline items
* [x] Style "delete" option in related item's heading
* [x] Make text/select/textarea inputs in StackedInline forms full-width
* [x] Test how `CheckboxSelectMultiple`, `RadioSelect` and Many2Many inputs work with those changes
* [x] Test how Filer and CKEditor inputs work with those changes
* [x] Test how changes influence existing RWD

I've no idea when I'll be able to wrap up those todos, but I'm expecting to slog trough them over coming weekends.

### CODE REVIEW

**Comment by rafalp** [comment]
Here's two screenshots of changes implemented by this PR:

screencapture-127-0-0-1-8000-admin-devapp-littleleague-1-change-1504475191413

screencapture-127-0-0-1-8000-admin-devapp-league-add-1504475223747

**Comment by rafalp** [comment]
I've removed compiled css file from PR and fixed filtered m2m fields to look like ones outside of related container (seems like they get overriden by some other rule):

zrzut ekranu 2017-09-04 o 00 07 16

**Comment by FinalAngel** [comment]
@vxsx would you be able to have a look at here?

**Comment by vxsx** [comment]
Looks good. Test are failing due to other things, but i can take it from here

**Comment by vxsx** [comment]
rebased / merged into master, sorry for the delay and thanks a lot!

**Pull request closed without merging**
