### PR TITLE
CMS- 384 updates changelist header and padding

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- https://divio-ch.atlassian.net/browse/CMS-384

Before:
jira-capture-screenshot-20150905-200053-448

After: 
screen shot 2015-09-07 at 14 56 31

### CODE REVIEW

**Comment by Brankub** [comment]
Could we use https://fortawesome.github.io/Font-Awesome/icons/ on the project? In this case we can use http://fortawesome.github.io/Font-Awesome/icon/check-circle/ instead of gif, for example. In this case it will looks nice on Retina.

**Comment by Brankub** [comment]
Or we can use it in Django MCS admin font

**Comment by lory87** [comment]
@Brankub unfortunately we can't because I can't change the template files. There is no class and only the gif which I have to overwrite :(

**Comment by Brankub** [comment]
ah, noooooooo :(. Okay, LGTM :ghost:

**Pull request merged**
