### PR TITLE
CMS-304 filer search and insertlink icon

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- https://divio-ch.atlassian.net/browse/CMS-304

BEFORE:
screen shot 2015-09-18 at 09 13 22

AFTER:
screen shot 2015-09-18 at 09 20 59

BEFORE:
screen shot 2015-09-18 at 09 16 06

AFTER:
screen shot 2015-09-18 at 09 19 24

### CODE REVIEW

**Comment by vxsx** [comment]
would it make sense to make "clipboard" title the same style as table headers

**Comment by lory87** [comment]
@vxsx was in the design like this. will add a comment for matthias to the ticket

**Comment by lory87** [comment]
@vxsx updated alignment

BEFORE:
screen shot 2015-09-18 at 09 49 39

AFTER:
screen shot 2015-09-18 at 09 56 34

**Comment by vxsx** [comment]
:+1:

**Pull request merged**
