### PR TITLE
fixes submit row button position on mobile view

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|
|---|---|
|screen shot 2015-10-07 at 10 44 26|screen shot 2015-10-07 at 10 52 07|

### CODE REVIEW

**Comment by Brankub** [comment]
LGTM

**Comment by vxsx** [comment]
from the code it doesn't seem that this will only happen on mobile

**Comment by Brankub** [comment]
@vxsx https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/djangocms-admin.scss

**Comment by Brankub** [comment]
@lory87 please check thatrule max-width: 420px: https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/djangocms-admin.scss gives a right result for your changes

**Comment by vxsx** [comment]
ah, then :+1:

**Comment by lory87** [comment]
@Brankub checked already before I made this pull request :) it's looks good on landscape mode

**Comment by Brankub** [comment]
@lory87 LGTM then again

**Pull request merged**
