### PR TITLE
Fixes button and language placement

### PR DESCRIPTION
**Pull request by FinalAngel**
**Before**
image

**After**
image

### CODE REVIEW

**Comment by vxsx** [comment]
:+1:

**Comment by mkoistinen** [comment]
The History button is hidden, we need this for reversion support.

**Comment by FinalAngel** [comment]
updated @mkoistinen

**Comment by mkoistinen** [comment]
Gorgeous! LGTM!

**Comment by mkoistinen** [comment]
I think this treatment should be done for HVAD apps too.

**Pull request merged**
