### PR TITLE
CMS-640 delete button

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- https://divio-ch.atlassian.net/browse/CMS-460

|BEFORE|AFTER|
|---|---|
|screen shot 2015-09-24 at 11 49 51|screen shot 2015-09-24 at 12 08 04|

### CODE REVIEW

**Comment by vxsx** [comment]
the spacing is incorrect

**Comment by lory87** [comment]
@vxsx thank you and corrected
screen shot 2015-09-24 at 12 17 13

**Comment by lory87** [comment]
@vxsx sorry didn't realized. Thought something different ;)
but now looks good
screen shot 2015-09-24 at 12 25 37

**Comment by vxsx** [comment]
:+1:

**Pull request merged**
