### PR TITLE
Updates login screen

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|CMS|
|---|---|---|
|screen shot 2015-10-06 at 12 05 10|screen shot 2015-10-06 at 13 05 03|screen shot 2015-10-06 at 12 05 41|

### CODE REVIEW

**Comment by FinalAngel** [comment]
how do the error messages look like?

**Comment by FinalAngel** [comment]
code LGTM

**Comment by lory87** [comment]
screen shot 2015-10-06 at 13 10 45

as in the whole admin forms

**Comment by FinalAngel** [comment]
LGTM

**Pull request merged**
