### PR TITLE
updates shortcuts styles

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|
|---|---|
|old|screen shot 2015-10-09 at 13 26 03|

### CODE REVIEW

**Comment by vxsx** [comment]
seems misaligned on the left

**Comment by lory87** [comment]
@vxsx thank you. 
screen shot 2015-10-09 at 13 31 27

**Comment by vxsx** [comment]
:+1:

**Comment by FinalAngel** [comment]
LGTM

**Pull request merged**
