### PR TITLE
fixes textarea height and input width

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|
|---|---|
|screen shot 2016-06-27 at 13 41 07|screen shot 2016-06-27 at 13 40 03|
|screen shot 2016-06-27 at 13 41 12|--|

### CODE REVIEW

**Comment by lory87** [comment]
@vxsx Screenshot test are not possible in this case at the moment because this fields are not available in djangocms admin style

**Comment by vxsx** [comment]
👍

**Comment by lory87** [comment]
https://github.com/divio/djangocms-admin-style/issues/354

**Comment by lory87** [comment]
https://github.com/divio/djangocms-admin-style/issues/355

**Pull request merged**
