### PR TITLE
Bugfix/updates messages

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|
|---|---|
|capture-for-jira-screenshot-20151003-140959-812|screen shot 2015-10-06 at 08 38 15|
|---|screen shot 2015-10-06 at 08 38 31|
|---|screen shot 2015-10-06 at 08 38 40|

### CODE REVIEW

**Comment by FinalAngel** [comment]
codewise LGTM, why is the bar not centered?

**Comment by lory87** [comment]
@FinalAngel because Matthias didn't center the bar in his layout. Thought the same.

**Comment by FinalAngel** [comment]
I'd double check, thats seemed weird for me :) :

**Comment by lory87** [comment]
@FinalAngel centered the messages and will add a comment to the ticket :)

**Comment by vxsx** [comment]
:

**Pull request merged**
