### PR TITLE
Show site name

### PR DESCRIPTION
**Pull request by mkoistinen**
The previous implementation of branding.html used the tag `{{ request.site.name }}` to create the label for the button "Open my site" with the intention that "my site" is replaced by the site's name. Unfortunately, this won't work without the middleware: `django.contrib.sites.middleware.CurrentSiteMiddleware`. Further, the instructions for installing django CMS does not direct users to install this middleware, nor is it installed by by the djangocms-installer package, nor is it installed by Aldryn by default.

To avoid having to change all of these packages/services to use this middleware, I've updated the `branding.html` template to use a simple templatetag which obtains the current site object through the recommended means and returns its name.

### CODE REVIEW

**Comment by mkoistinen** [comment]
@czpython and @vxsx / @lory87 please review.

**Comment by vxsx** [comment]
LGTM, but you will need to update the screenshots/reference folder with these files
[new-reference.zip](https://github.com/divio/djangocms-admin-style/files/336464/new-reference.zip)

**Comment by vxsx** [comment]
@mkoistinen can you rebase and adapt screenshots?

**Comment by mkoistinen** [comment]
Thank you!

**Pull request merged**
